name: server

on:
  push:
    branches: [master]

jobs:
  style:
    name: check prettier and type checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: install deps
        run: npm i

      - name: build
        run: npm run build
